# Services
services:

  # Nginx Service
  nginx:
    container_name: web
    image: nginx:alpine
    ports:
      - 8080:80
      - 443:443
    restart: always
    environment:
      - TZ=America/Edmonton
    links:
      - php
    volumes:
      - ./www/html/:/var/www/html/
      - ./nginx/conf/default-ssl.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs/:/var/log/nginx/
      - ./devcerts/:/etc/nginx/certs/
    depends_on:
      - php
    networks:
      - lemp-sqlite3-net

  # PHP-FPM Service
  php:
    container_name: php8
    build: php
    expose:
      - 9000
    restart: always
    environment:
      - TZ=America/Edmonton
    volumes:
      - ./www/html/:/var/www/html/
      # php-fpm config files are located at /usr/local/etc/php-fpm.d/ folder
      - ./php/php-log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./db/data/:/data/
    networks:
      - lemp-sqlite3-net

  # SQLiteBrowser Service
  sqlitebrowser:
    container_name: sqlitebrowser
    image: evgeniydoctor/sqlitebrowser:latest
    ports:
      - 5800:5800
    restart: unless-stopped
    environment:
      - VNC_PASSWORD=vncP@ss2024
      - KEEP_APP_RUNNING=1
      - TZ=America/Edmonton
    volumes:
      - ./db/dir:/dbs/dir
      - ./db/data:/dbs/data
    depends_on: 
      - php
    networks:
      - lemp-sqlite3-net

# Networks
networks:
  lemp-sqlite3-net:
